
// Data types

// Define the data types
export interface CartItem {
  id: string;
  quantity: number;
}

export interface Medicine {
  id: string;
  name: string;
  description: string;
  price: number;
  marketPrice: number;
  discountPercentage: number;
  imageUrl: string;
  category: string;
  inStock: boolean;
  ayurvedic?: boolean;
  wholesaleOnly?: boolean;
  wholesalePrice?: number;
}

// Define the categories
export const categories = [
  'All',
  'Prescription',
  'OTC Medicines',
  'Ayurvedic',
  'Supplements',
  'Skincare',
  'Personal Care',
  'Baby Care',
  'Health Devices',
  'Wholesale Only'
];

// Import medicine images
import amoxicillinImg from '@/assets/medicines/amoxicillin.jpg';
import lisinoprilImg from '@/assets/medicines/lisinopril.jpg';
import metforminImg from '@/assets/medicines/metformin.jpg';
import atorvastatinImg from '@/assets/medicines/atorvastatin.jpg';
import losartanImg from '@/assets/medicines/losartan.jpg';
import paracetamolImg from '@/assets/medicines/paracetamol.jpg';
import cetrizineImg from '@/assets/medicines/cetrizine.jpg';
import coughSyrupImg from '@/assets/medicines/cough-syrup.jpg';
import ibuprofenImg from '@/assets/medicines/ibuprofen.jpg';
import antacidImg from '@/assets/medicines/antacid.jpg';
import ashwagandhaImg from '@/assets/medicines/ashwagandha.jpg';
import chyawanprashImg from '@/assets/medicines/chyawanprash.jpg';
import triphalaImg from '@/assets/medicines/triphala.jpg';
import tulsiDropsImg from '@/assets/medicines/tulsi-drops.jpg';
import giloyImg from '@/assets/medicines/giloy.jpg';
import multivitaminImg from '@/assets/medicines/multivitamin.jpg';
import omega3Img from '@/assets/medicines/omega3.jpg';
import proteinPowderImg from '@/assets/medicines/protein-powder.jpg';
import calciumD3Img from '@/assets/medicines/calcium-d3.jpg';
import ironFolicImg from '@/assets/medicines/iron-folic.jpg';
import moisturizerImg from '@/assets/medicines/moisturizer.jpg';
import acneGelImg from '@/assets/medicines/acne-gel.jpg';
import vitaminCSerumImg from '@/assets/medicines/vitamin-c-serum.jpg';
import sunscreenImg from '@/assets/medicines/sunscreen.jpg';
import nightCreamImg from '@/assets/medicines/night-cream.jpg';
import hyaluronicSerumImg from '@/assets/medicines/hyaluronic-serum.jpg';
import handSanitizerImg from '@/assets/medicines/hand-sanitizer.jpg';
import dentalFlossImg from '@/assets/medicines/dental-floss.jpg';
import electricToothbrushImg from '@/assets/medicines/electric-toothbrush.jpg';
import mouthwashImg from '@/assets/medicines/mouthwash.jpg';
import medicatedShampooImg from '@/assets/medicines/medicated-shampoo.jpg';
import diaperCreamImg from '@/assets/medicines/diaper-cream.jpg';
import babyShampooImg from '@/assets/medicines/baby-shampoo.jpg';
import babyPowderImg from '@/assets/medicines/baby-powder.jpg';
import babyWipesImg from '@/assets/medicines/baby-wipes.jpg';
import thermometerImg from '@/assets/medicines/thermometer.jpg';
import bpMonitorImg from '@/assets/medicines/bp-monitor.jpg';
import pulseOximeterImg from '@/assets/medicines/pulse-oximeter.jpg';
import nebulizerImg from '@/assets/medicines/nebulizer.jpg';
import glucoseMonitorImg from '@/assets/medicines/glucose-monitor.jpg';
import surgicalMasksImg from '@/assets/medicines/surgical-masks.jpg';
import disposableGlovesImg from '@/assets/medicines/disposable-gloves.jpg';
import alcoholSwabsImg from '@/assets/medicines/alcohol-swabs.jpg';
import disinfectantImg from '@/assets/medicines/disinfectant.jpg';
import cottonRollImg from '@/assets/medicines/cotton-roll.jpg';
import surgicalTapeImg from '@/assets/medicines/surgical-tape.jpg';

// Define the medicines data
export const medicines: Medicine[] = [
  // Prescription Medicines
  {
    id: 'med1',
    name: 'Amoxicillin 500mg',
    description: 'Antibiotic for bacterial infections',
    price: 380,
    marketPrice: 450,
    discountPercentage: 16,
    imageUrl: amoxicillinImg,
    category: 'Prescription',
    inStock: true,
    wholesalePrice: 320,
  },
  {
    id: 'med2',
    name: 'Lisinopril 10mg',
    description: 'For high blood pressure management',
    price: 420,
    marketPrice: 490,
    discountPercentage: 14,
    imageUrl: lisinoprilImg,
    category: 'Prescription',
    inStock: true,
    wholesalePrice: 350,
  },
  {
    id: 'med3',
    name: 'Metformin 500mg',
    description: 'For type 2 diabetes',
    price: 350,
    marketPrice: 400,
    discountPercentage: 13,
    imageUrl: metforminImg,
    category: 'Prescription',
    inStock: false,
    wholesalePrice: 290,
  },
  {
    id: 'med3a',
    name: 'Atorvastatin 20mg',
    description: 'For cholesterol management',
    price: 450,
    marketPrice: 520,
    discountPercentage: 13,
    imageUrl: atorvastatinImg,
    category: 'Prescription',
    inStock: true,
    wholesalePrice: 380,
  },
  {
    id: 'med3b',
    name: 'Losartan 50mg',
    description: 'For hypertension treatment',
    price: 380,
    marketPrice: 440,
    discountPercentage: 14,
    imageUrl: losartanImg,
    category: 'Prescription',
    inStock: true,
    wholesalePrice: 320,
  },

  // OTC Medicines
  {
    id: 'med4',
    name: 'Paracetamol 500mg',
    description: 'Pain reliever and fever reducer',
    price: 120,
    marketPrice: 150,
    discountPercentage: 20,
    imageUrl: paracetamolImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 85,
  },
  {
    id: 'med5',
    name: 'Cetrizine 10mg',
    description: 'Antihistamine for allergies',
    price: 180,
    marketPrice: 200,
    discountPercentage: 18,
    imageUrl: cetrizineImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 140,
  },
  {
    id: 'med6',
    name: 'Cough Syrup',
    description: 'For dry and productive cough',
    price: 240,
    marketPrice: 280,
    discountPercentage: 15,
    imageUrl: coughSyrupImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 180,
  },
  {
    id: 'med6a',
    name: 'Ibuprofen 400mg',
    description: 'Anti-inflammatory pain reliever',
    price: 160,
    marketPrice: 190,
    discountPercentage: 16,
    imageUrl: ibuprofenImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 130,
  },
  {
    id: 'med6b',
    name: 'Antacid Suspension',
    description: 'For heartburn and acidity',
    price: 190,
    marketPrice: 220,
    discountPercentage: 14,
    imageUrl: antacidImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 150,
  },
  {
    id: 'otc_aspirin',
    name: 'Aspirin 325mg',
    description: 'Relieves pain, fever, and inflammation',
    price: 140,
    marketPrice: 170,
    discountPercentage: 17,
    imageUrl: paracetamolImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 100,
  },
  {
    id: 'otc_loperamide',
    name: 'Loperamide 2mg',
    description: 'Fast-acting anti-diarrheal medication',
    price: 110,
    marketPrice: 130,
    discountPercentage: 15,
    imageUrl: ibuprofenImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 80,
  },
  {
    id: 'otc_diphenhydramine',
    name: 'Diphenhydramine 25mg',
    description: 'Antihistamine for allergies and sleep aid',
    price: 130,
    marketPrice: 160,
    discountPercentage: 18,
    imageUrl: cetrizineImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 95,
  },
  {
    id: 'otc_loratadine',
    name: 'Loratadine 10mg',
    description: '24-hour non-drowsy allergy relief',
    price: 210,
    marketPrice: 250,
    discountPercentage: 16,
    imageUrl: cetrizineImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 150,
  },
  {
    id: 'otc_dextromethorphan',
    name: 'Dextromethorphan Syrup',
    description: 'Cough suppressant for dry cough relief',
    price: 195,
    marketPrice: 230,
    discountPercentage: 15,
    imageUrl: coughSyrupImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 140,
  },
  {
    id: 'otc_hydrocortisone',
    name: 'Hydrocortisone Cream 1%',
    description: 'Relieves itching, redness, and swelling',
    price: 175,
    marketPrice: 210,
    discountPercentage: 16,
    imageUrl: acneGelImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 130,
  },
  {
    id: 'otc_bismuth',
    name: 'Bismuth Subsalicylate',
    description: 'Soothing relief for upset stomach and indigestion',
    price: 220,
    marketPrice: 260,
    discountPercentage: 15,
    imageUrl: antacidImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 160,
  },
  {
    id: 'otc_famotidine',
    name: 'Famotidine 20mg',
    description: 'Acid reducer for heartburn relief',
    price: 180,
    marketPrice: 220,
    discountPercentage: 18,
    imageUrl: paracetamolImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 135,
  },
  {
    id: 'otc_guaifenesin',
    name: 'Guaifenesin 400mg',
    description: 'Expectorant to thin mucus and clear chest congestion',
    price: 230,
    marketPrice: 270,
    discountPercentage: 14,
    imageUrl: ibuprofenImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 170,
  },
  {
    id: 'otc_phenylephrine',
    name: 'Phenylephrine Nasal Spray',
    description: 'Fast nasal decongestant spray',
    price: 150,
    marketPrice: 180,
    discountPercentage: 16,
    imageUrl: tulsiDropsImg,
    category: 'OTC Medicines',
    inStock: true,
    wholesalePrice: 110,
  },

  // Ayurvedic
  {
    id: 'med7',
    name: 'Ashwagandha Tablets',
    description: 'For stress and anxiety relief',
    price: 350,
    marketPrice: 420,
    discountPercentage: 17,
    imageUrl: ashwagandhaImg,
    category: 'Ayurvedic',
    inStock: true,
    ayurvedic: true,
    wholesalePrice: 280,
  },
  {
    id: 'med8',
    name: 'Chyawanprash',
    description: 'Immunity booster',
    price: 420,
    marketPrice: 480,
    discountPercentage: 16,
    imageUrl: chyawanprashImg,
    category: 'Ayurvedic',
    inStock: true,
    ayurvedic: true,
    wholesalePrice: 350,
  },
  {
    id: 'med9',
    name: 'Triphala Tablets',
    description: 'For digestive health',
    price: 280,
    marketPrice: 320,
    discountPercentage: 14,
    imageUrl: triphalaImg,
    category: 'Ayurvedic',
    inStock: true,
    ayurvedic: true,
    wholesalePrice: 250,
  },
  {
    id: 'med9a',
    name: 'Tulsi Drops',
    description: 'Herbal immune support',
    price: 220,
    marketPrice: 250,
    discountPercentage: 12,
    imageUrl: tulsiDropsImg,
    category: 'Ayurvedic',
    inStock: true,
    ayurvedic: true,
    wholesalePrice: 180,
  },
  {
    id: 'med9b',
    name: 'Giloy Tablets',
    description: 'Boosts immunity and fights infections',
    price: 250,
    marketPrice: 290,
    discountPercentage: 14,
    imageUrl: giloyImg,
    category: 'Ayurvedic',
    inStock: true,
    ayurvedic: true,
    wholesalePrice: 210,
  },

  // Supplements
  {
    id: 'med10',
    name: 'Multivitamin Tablets',
    description: 'Complete daily vitamins and minerals',
    price: 580,
    marketPrice: 650,
    discountPercentage: 11,
    imageUrl: multivitaminImg,
    category: 'Supplements',
    inStock: true,
    wholesalePrice: 480,
  },
  {
    id: 'med11',
    name: 'Omega-3 Fish Oil',
    description: 'For heart and brain health',
    price: 650,
    marketPrice: 750,
    discountPercentage: 12,
    imageUrl: omega3Img,
    category: 'Supplements',
    inStock: true,
    wholesalePrice: 550,
  },
  {
    id: 'med12',
    name: 'Protein Powder',
    description: 'For muscle recovery and growth',
    price: 1200,
    marketPrice: 1400,
    discountPercentage: 10,
    imageUrl: proteinPowderImg,
    category: 'Supplements',
    inStock: true,
    wholesalePrice: 1000,
  },
  {
    id: 'med12a',
    name: 'Calcium + Vitamin D3',
    description: 'For bone health and strength',
    price: 450,
    marketPrice: 520,
    discountPercentage: 13,
    imageUrl: calciumD3Img,
    category: 'Supplements',
    inStock: true,
    wholesalePrice: 380,
  },
  {
    id: 'med12b',
    name: 'Iron + Folic Acid',
    description: 'For anemia and pregnancy support',
    price: 380,
    marketPrice: 420,
    discountPercentage: 10,
    imageUrl: ironFolicImg,
    category: 'Supplements',
    inStock: true,
    wholesalePrice: 320,
  },
  
  // Skincare
  {
    id: 'skin1',
    name: 'Moisturizing Cream',
    description: 'Hydrates and nourishes dry skin',
    price: 450,
    marketPrice: 520,
    discountPercentage: 13,
    imageUrl: moisturizerImg,
    category: 'Skincare',
    inStock: true,
    wholesalePrice: 380,
  },
  {
    id: 'skin2',
    name: 'Acne Treatment Gel',
    description: 'Reduces acne and prevents breakouts',
    price: 320,
    marketPrice: 380,
    discountPercentage: 12,
    imageUrl: acneGelImg,
    category: 'Skincare',
    inStock: true,
    wholesalePrice: 280,
  },
  {
    id: 'skin3',
    name: 'Vitamin C Serum',
    description: 'Brightens skin and reduces dark spots',
    price: 780,
    marketPrice: 900,
    discountPercentage: 15,
    imageUrl: vitaminCSerumImg,
    category: 'Skincare',
    inStock: true,
    wholesalePrice: 700,
  },
  {
    id: 'skin4',
    name: 'Sunscreen SPF 50',
    description: 'Protects skin from harmful UV rays',
    price: 520,
    marketPrice: 600,
    discountPercentage: 14,
    imageUrl: sunscreenImg,
    category: 'Skincare',
    inStock: true,
    wholesalePrice: 480,
  },
  {
    id: 'skin5',
    name: 'Anti-aging Night Cream',
    description: 'Reduces fine lines and wrinkles',
    price: 850,
    marketPrice: 950,
    discountPercentage: 11,
    imageUrl: nightCreamImg,
    category: 'Skincare',
    inStock: true,
    wholesalePrice: 720,
  },
  {
    id: 'skin6',
    name: 'Hyaluronic Acid Serum',
    description: 'Deep hydration for all skin types',
    price: 680,
    marketPrice: 780,
    discountPercentage: 13,
    imageUrl: hyaluronicSerumImg,
    category: 'Skincare',
    inStock: true,
    wholesalePrice: 590,
  },
  
  // Personal Care
  {
    id: 'pc1',
    name: 'Hand Sanitizer',
    description: 'Kills 99.9% of germs without water',
    price: 150,
    marketPrice: 180,
    discountPercentage: 17,
    imageUrl: handSanitizerImg,
    category: 'Personal Care',
    inStock: true,
    wholesalePrice: 120,
  },
  {
    id: 'pc2',
    name: 'Dental Floss',
    description: 'For effective plaque removal',
    price: 120,
    marketPrice: 140,
    discountPercentage: 16,
    imageUrl: dentalFlossImg,
    category: 'Personal Care',
    inStock: true,
    wholesalePrice: 100,
  },
  {
    id: 'pc3',
    name: 'Electric Toothbrush',
    description: 'Advanced cleaning technology',
    price: 1800,
    marketPrice: 2200,
    discountPercentage: 18,
    imageUrl: electricToothbrushImg,
    category: 'Personal Care',
    inStock: true,
    wholesalePrice: 1600,
  },
  {
    id: 'pc4',
    name: 'Mouthwash',
    description: 'Alcohol-free antibacterial rinse',
    price: 280,
    marketPrice: 320,
    discountPercentage: 13,
    imageUrl: mouthwashImg,
    category: 'Personal Care',
    inStock: true,
    wholesalePrice: 240,
  },
  {
    id: 'pc5',
    name: 'Medicated Shampoo',
    description: 'For dandruff and scalp conditions',
    price: 340,
    marketPrice: 380,
    discountPercentage: 11,
    imageUrl: medicatedShampooImg,
    category: 'Personal Care',
    inStock: true,
    wholesalePrice: 280,
  },
  
  // Baby Care
  {
    id: 'baby1',
    name: 'Baby Diaper Rash Cream',
    description: 'Soothes and protects sensitive skin',
    price: 280,
    marketPrice: 320,
    discountPercentage: 13,
    imageUrl: diaperCreamImg,
    category: 'Baby Care',
    inStock: true,
    wholesalePrice: 220,
  },
  {
    id: 'baby2',
    name: 'Baby Shampoo',
    description: 'Gentle, tear-free formula',
    price: 320,
    marketPrice: 380,
    discountPercentage: 14,
    imageUrl: babyShampooImg,
    category: 'Baby Care',
    inStock: true,
    wholesalePrice: 280,
  },
  {
    id: 'baby3',
    name: 'Baby Powder',
    description: 'Talc-free, safe for sensitive skin',
    price: 180,
    marketPrice: 210,
    discountPercentage: 14,
    imageUrl: babyPowderImg,
    category: 'Baby Care',
    inStock: true,
    wholesalePrice: 150,
  },
  {
    id: 'baby4',
    name: 'Baby Wipes',
    description: 'Alcohol-free and hypoallergenic',
    price: 120,
    marketPrice: 140,
    discountPercentage: 14,
    imageUrl: babyWipesImg,
    category: 'Baby Care',
    inStock: true,
    wholesalePrice: 90,
  },
  
  // Health Devices
  {
    id: 'device1',
    name: 'Digital Thermometer',
    description: 'Fast and accurate temperature reading',
    price: 550,
    marketPrice: 620,
    discountPercentage: 11,
    imageUrl: thermometerImg,
    category: 'Health Devices',
    inStock: true,
    wholesalePrice: 450,
  },
  {
    id: 'device2',
    name: 'Blood Pressure Monitor',
    description: 'For home BP monitoring',
    price: 2200,
    marketPrice: 2600,
    discountPercentage: 15,
    imageUrl: bpMonitorImg,
    category: 'Health Devices',
    inStock: true,
    wholesalePrice: 1800,
  },
  {
    id: 'device3',
    name: 'Pulse Oximeter',
    description: 'Measures blood oxygen levels',
    price: 1800,
    marketPrice: 2200,
    discountPercentage: 16,
    imageUrl: pulseOximeterImg,
    category: 'Health Devices',
    inStock: true,
    wholesalePrice: 1600,
  },
  {
    id: 'device4',
    name: 'Nebulizer',
    description: 'For respiratory medication delivery',
    price: 1600,
    marketPrice: 1900,
    discountPercentage: 16,
    imageUrl: nebulizerImg,
    category: 'Health Devices',
    inStock: true,
    wholesalePrice: 1400,
  },
  {
    id: 'device5',
    name: 'Glucose Monitor Kit',
    description: 'Complete diabetes monitoring solution',
    price: 2800,
    marketPrice: 3200,
    discountPercentage: 13,
    imageUrl: glucoseMonitorImg,
    category: 'Health Devices',
    inStock: true,
    wholesalePrice: 2400,
  },
  
  // Wholesale Only Products
  {
    id: 'wholesale1',
    name: 'Surgical Masks (Box of 100)',
    description: 'Disposable 3-ply surgical masks',
    price: 1200,
    marketPrice: 1500,
    discountPercentage: 20,
    imageUrl: surgicalMasksImg,
    category: 'Wholesale Only',
    inStock: true,
    wholesaleOnly: true,
    wholesalePrice: 900,
  },
  {
    id: 'wholesale2',
    name: 'Disposable Gloves (Box of 200)',
    description: 'Latex-free disposable examination gloves',
    price: 1800,
    marketPrice: 2200,
    discountPercentage: 18,
    imageUrl: disposableGlovesImg,
    category: 'Wholesale Only',
    inStock: true,
    wholesaleOnly: true,
    wholesalePrice: 1400,
  },
  {
    id: 'wholesale3',
    name: 'Alcohol Swabs (Pack of 500)',
    description: 'Individually wrapped alcohol prep pads',
    price: 950,
    marketPrice: 1100,
    discountPercentage: 14,
    imageUrl: alcoholSwabsImg,
    category: 'Wholesale Only',
    inStock: true,
    wholesaleOnly: true,
    wholesalePrice: 750,
  },
  {
    id: 'wholesale4',
    name: 'Disinfectant Solution (5L)',
    description: 'Hospital grade disinfectant concentrate',
    price: 1500,
    marketPrice: 1800,
    discountPercentage: 17,
    imageUrl: disinfectantImg,
    category: 'Wholesale Only',
    inStock: true,
    wholesaleOnly: true,
    wholesalePrice: 1200,
  },
  {
    id: 'wholesale5',
    name: 'Cotton Roll (500g)',
    description: 'Medical grade absorbent cotton',
    price: 850,
    marketPrice: 950,
    discountPercentage: 11,
    imageUrl: cottonRollImg,
    category: 'Wholesale Only',
    inStock: true,
    wholesaleOnly: true,
    wholesalePrice: 720,
  },
  {
    id: 'wholesale6',
    name: 'Surgical Tape (Box of 24)',
    description: 'Hypoallergenic medical tape',
    price: 720,
    marketPrice: 840,
    discountPercentage: 14,
    imageUrl: surgicalTapeImg,
    category: 'Wholesale Only',
    inStock: true,
    wholesaleOnly: true,
    wholesalePrice: 600,
  },
];
